// layout types
export const TOGGLE_MENU = "TOGGLE_MENU";
export const SET_MENU_ICON = "SET_MENU_ICON";
export const SET_MENU_TITLE = "SET_MENU_TITLE";
export const MENU_COLLAPSE = "MENU_COLLAPSE";
export const SET_MENU_SELECTED = "SET_MENU_SELECTED";

// loading types
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

//searchVisits

export const LOAD_STREETS_SUCCESS = "LOAD_STREETS_SUCCESS";
export const LOAD_STREET_NUMBERS_SUCCESS = "LOAD_STREET_NUMBERS_SUCCESS";
export const LOAD_PENDING_VISITS_SUCCESS = "LOAD_PENDING_VISITS_SUCCESS";
export const LOAD_USERS_IN_ADDRESS_SUCCESS = "LOAD_USERS_IN_ADDRESS_SUCCESS";
export const SET_SELECTED_STREET = "SET_SELECTED_STREET";
export const SET_SELECTED_STREET_NUMBER = "SET_SELECTED_STREET_NUMBER";
export const SET_SELECTED_PENDING_VISIT = "SET_SELECTED_PENDING_VISIT";
export const CLEAN_STREETS = "CLEAN_STREETS";
export const CLEAN_STREET_NUMBERS = "CLEAN_STREET_NUMBERS";
export const CLEAN_USERS_IN_ADDRESS = "CLEAN_USERS_IN_ADDRESS";
export const CLEAN_PENDING_VISITS = "CLEAN_PENDING_VISITS";

// auth types
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// user types
export const LOAD_USER_FAVS_SUCCESS = "LOAD_USER_FAVS_SUCCESS";
export const ADD_USER_FAV_SUCCESS = "ADD_USER_FAV_SUCCESS";
export const REMOVE_USER_FAV_SUCCESS = "REMOVE_USER_FAV_SUCCESS";
export const ADD_USER_GUEST = "ADD_USER_GUEST";
export const REMOVE_USER_GUEST = "REMOVE_USER_GUEST";
export const CLEAN_USER_GUEST = "CLEAN_USER_GUEST";
export const UPDATE_USER_GUEST = "UPDATE_USER_GUEST";
export const GET_SUBURB_DATA_SUCCESS = "GET_SUBURB_DATA_SUCCESS";
export const ADD_SUBURB_INVITE_SUCCESS = "ADD_SUBURB_INVITE_SUCCESS";
export const CLEAR_SUBURB_INVITE = "CLEAR_SUBURB_INVITE";
export const GET_INVITE_BY_CODE_SUCCESS = "GET_INVITE_BY_CODE_SUCCESS";
export const CLEAN_USER_INVITE = "CLEAN_USER_INVITE";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_TERMS_SUCCESS = "GET_TERMS_SUCCESS";
export const SING_TERMS_SUCCESS = "SING_TERMS_SUCCESS";
export const GENERATE_TEMP_PASS_SUCCESS = "GENERATE_TEMP_PASS_SUCCESS";
export const SET_TEMPORARY_PASS = "SET_TEMPORARY_PASS";
export const SAVE_TEMP_PASS = "SAVE_TEMP_PASS";

export const ADD_INVITE_SUCCESS = "ADD_INVITE_SUCCESS";
export const CLEAN_INVITE = "CLEAN_INVITE";
export const UPDATE_USER_PICTURE_SUCCESS = "UPDATE_USER_PICTURE_SUCCESS";


//suburb config

export const LOAD_SUBURB_CONFIG_SUCCESS = "LOAD_SUBURB_CONFIG_SUCCESS";


//MyVisits

export const LOAD_MY_VISITS_SUCCESS = "LOAD_MY_VISITS_SUCCESS";
export const DELETE_VISIT_SUCCESS = "DELETE_VISIT_SUCCESS";